apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-test-sc
  annotations:
    openebs.io/cas-type: cstor
    storageclass.kubernetes.io/is-default-class: "true"
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-pool-openebs-test-sc"
      - name: ReplicaCount
        value: "3"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: "Retain"
